# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e912194924e05ae3e24573d28d4743eaacab64b372ebbb25c954bf9e17aa5b9e42d09062d81e3e531ec8368afc1749fb53738942c4c1ed2c2dc975f515493c93

test:
  secret_key_base: df05d3a54c1380e806e7f5a008302dfb0330f72f152403632e571462665d3ed6207915ce82af4be532ef8b49a9ddc90d4a7cd94162d2e349e4b1f2d969ff3dc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
